// <auto-generated />
using System;
using FMDL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FMDL.Migrations
{
    [DbContext(typeof(FluffyDBContext))]
    [Migration("20210312213104_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FMModels.Fluffymon", b =>
                {
                    b.Property<int>("FluffymonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AES")
                        .HasColumnType("integer");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<int>("Fluffiness")
                        .HasColumnType("integer");

                    b.Property<string>("FluffymonName")
                        .HasColumnType("text");

                    b.Property<int>("MGTR")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FluffymonId");

                    b.HasIndex("UserId");

                    b.ToTable("Fluffymons");

                    b.HasData(
                        new
                        {
                            FluffymonId = 1,
                            AES = 18,
                            Element = 1,
                            Fluffiness = 30,
                            FluffymonName = "CommieMon",
                            MGTR = 10
                        },
                        new
                        {
                            FluffymonId = 2,
                            AES = 50,
                            Element = 3,
                            Fluffiness = 20,
                            FluffymonName = "WestonMon",
                            MGTR = 14
                        },
                        new
                        {
                            FluffymonId = 3,
                            AES = 25,
                            Element = 5,
                            Fluffiness = 40,
                            FluffymonName = "DoomerMon",
                            MGTR = 15
                        },
                        new
                        {
                            FluffymonId = 4,
                            AES = 30,
                            Element = 4,
                            Fluffiness = 20,
                            FluffymonName = "PokeMon",
                            MGTR = 20
                        },
                        new
                        {
                            FluffymonId = 5,
                            AES = 30,
                            Element = 2,
                            Fluffiness = 50,
                            FluffymonName = "CommeTankMon",
                            MGTR = 5
                        });
                });

            modelBuilder.Entity("FMModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("UserHp")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FMModels.UserFluffymon", b =>
                {
                    b.Property<int>("FluffymonId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserFluffymonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("FluffymonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFluffymons");
                });

            modelBuilder.Entity("FMModels.Fluffymon", b =>
                {
                    b.HasOne("FMModels.User", null)
                        .WithMany("Fluffymon")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FMModels.UserFluffymon", b =>
                {
                    b.HasOne("FMModels.Fluffymon", "Fluffymon")
                        .WithMany("UserFluffymon")
                        .HasForeignKey("FluffymonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fluffymon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMModels.Fluffymon", b =>
                {
                    b.Navigation("UserFluffymon");
                });

            modelBuilder.Entity("FMModels.User", b =>
                {
                    b.Navigation("Fluffymon");
                });
#pragma warning restore 612, 618
        }
    }
}
